{
 "title": "Pensu Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raw Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(my_stats.pensu_test_metrics.load.*, 10), 'load-5min-avg')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction.metrics_analyzer.my_stats.pensu_test_metrics.load.*, 10), 'htm-prediction')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction_confidence.metrics_analyzer.my_stats.pensu_test_metrics.load.*, 10), 'prediction-confidence')"
    }
   ]
  },
  {
   "title": "Raw Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(my_stats.pensu_test_metrics.memory.used, 10), 'memory-used')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 'htm-prediction')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction_confidence.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 'htm-prediction-confidence')"
    }
   ]
  },
  {
   "title": "Raw Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'network-rx-bytes-eth0')"
    },
    {
     "target": "alias(keepLastValue(my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'network-tx-bytes-eth0')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'htm-prediction-rx-eth0')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'htm-prediction-tx-eth0')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction_confidence.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'htm-prediction-confidence-rx-eth0')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction_confidence.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'htm-prediction-confidence-tx-eth0')"
    }
   ]
  },
  {
   "title": "Raw Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(my_stats.pensu_test_metrics.test_data, 10), 'test-data')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 'htm-prediction')"
    },
    {
     "target": "alias(keepLastValue(pensu.prediction_confidence.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 'htm-prediction-confidence')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Likelihood",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.load.5min_avg, 10), 'load-5min-avg-anomaly-likelihood')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.load.5min_avg, 10), 'anomaly-score')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.load.5min_avg, 10), 0.9), 'anomaly-score-high')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.load.5min_avg, 10), 0.99999), 'anomaly-likelihood-high')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Likelihood",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 'memory-used-anomaly-likelihood')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 'anomaly-score')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 0.9), 'anomaly-score-high')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 0.99999), 'anomaly-likelihood-high')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Likelihood",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'network-rx-bytes-eth0-anomaly-likelihood')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'network-tx-bytes-eth0-anomaly-likelihood')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'network-rx-bytes-eth0-anomaly-score')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'network-tx-bytes-eth0-anomaly-score')"
    },
    {
     "target": "removeBelowValue(alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'anomaly-score-high-rx-bytes-eth0'), 0.9)"
    },
    {
     "target": "removeBelowValue(alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'anomaly-score-high-tx-bytes-eth0'), 0.9)"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 0.99999), 'anomaly-likelihood-high-tx-bytes-eth0')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 0.99999), 'anomaly-likelihood-high-rx-bytes-eth0')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Likelihood",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 'test-data-anomaly-likelihood')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 'anomaly-score')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_score.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 0.9), 'anomaly-score-high')"
    },
    {
     "target": "alias(removeBelowValue(keepLastValue(pensu.anomaly_likelihood.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 0.99999), 'anomaly-likelihood-high')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_direction.metrics_analyzer.my_stats.pensu_test_metrics.load.5min_avg, 10), 'load-5min-avg-anomaly-direction')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_direction.metrics_analyzer.my_stats.pensu_test_metrics.memory.used, 10), 'memory-used-anomaly-direction')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_direction.metrics_analyzer.my_stats.pensu_test_metrics.network.rx_bytes.eth0, 10), 'network-rx-bytes-eth0-anomaly-direction')"
    },
    {
     "target": "alias(keepLastValue(pensu.anomaly_direction.metrics_analyzer.my_stats.pensu_test_metrics.network.tx_bytes.eth0, 10), 'network-tx-bytes-eth0-anomaly-direction')"
    }
   ]
  },
  {
   "title": "ML Metrics - Anomaly Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(pensu.anomaly_direction.metrics_analyzer.my_stats.pensu_test_metrics.test_data, 10), 'test-data-anomaly-direction')"
    }
   ]
  }
 ]
}